### ISSUE TITLE
Novice help

### ISSUE THREAD

**Issue by chanansh** [williballenthin/python-evtx#15]
I don't understand how to use this package withing python as an API.
I did `from Evtx.Evtx import Evtx` now I did `with Evtx(filename) as evtx: e=evtx.records() ` how do I read `e`'s content?

**Comment by williballenthin** [comment]
An EVTX record is essentially a binary XML node. In python-evtx, each record has a complex structure that matches the XML structure. This allows us to fetch any field and reconstruct the XML document in different ways. Typically, though, you'll convert the node into an XML string like in the samples `get_pretty_record.py` and `dumpevtx.py`:

```
    with Evtx(args.evtx) as evtx:
        record = evtx.get_record(args.record_id)
        if record is None:
            raise RuntimeError("Cannot find the record specified.")

        print("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\" ?>\n")
        print(evtx_record_xml_view(record))
```

**Comment by chanansh** [comment]
Thanks. What if I would like to enumreate on records? (I don't know the ids)

**Comment by williballenthin** [comment]
See the example here: https://github.com/williballenthin/python-evtx/blob/master/scripts/filter_records.py#L16
