### ISSUE TITLE
HTMLEntities instead utf8 characters in fields value

### ISSUE THREAD

**Issue by Sid-Vishez** [williballenthin/python-evtx#24]
Hello! All national symbols are encoded to HTMLEntities
![2016-08-03 1 24 57](https://cloud.githubusercontent.com/assets/2886098/17343967/287fd9fc-5922-11e6-990f-4a2862a0c342.png)

**Comment by williballenthin** [comment]
Hi @Sid-Vishez 

To be clear, are you requesting that the scripts be updated to encode the output as utf-8 rather than use the html entities fields?

**Comment by Sid-Vishez** [comment]
yes, exactly.

**Comment by williballenthin** [comment]
hi @Sid-Vishez 

i do not think this will be easy to do. we use the standard python xml sax encoder to format these values, and its this routine that has chosen to using html entities. i think a compliant xml parser should transparently decode these strings. are you having trouble doing this?
