### ISSUE TITLE
UnicodeEncodeError when stdout is redirected

### ISSUE THREAD

**Issue by patatetom** [williballenthin/python-evtx#25]
hi Willi,

I'm using the lasted python-evtx.
if I keep stdout in console and redirect stderr in a file, all is ok with no error :

```
# evtxdump /sdb2/Windows/System32/winevt/Logs/System.evtx 2>/tmp/evtxdump.error
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<Events>
...
</Events>
# cat /tmp/evtxdump.error
```

but if I redirect stdout to a file, I've got an encode error

```
# evtxdump /sdb2/Windows/System32/winevt/Logs/System.evtx >/tmp/evtxdump.dump
Traceback (most recent call last):
  File "/usr/local/bin/evtxdump", line 49, in <module>
    main()
  File "/usr/local/bin/evtxdump", line 45, in main
    print xml
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1253: ordinal not in range(128)
```

regards

**Comment by williballenthin** [comment]
hey @patatetom are you on python2 or python3? i want to reproduce this locally similar to your environment so i can fix it correctly.

**Comment by patatetom** [comment]
Hi Willy,
Sorry for response time :-(
I tried to reproduce this strange behavior (with python2) but did not succeed :-(
Sorry for the inconvenience :-(
Regards
