### ISSUE TITLE
AttributeError: 'module' object has no attribute 'XML_HEADER'

### ISSUE THREAD

**Issue by stephensheridan** [williballenthin/python-evtx#36]
Hi Will, 

Using the latest release and running evtxdump against an evtx file that parsed previously in version V0.3.2, I am getting the following error.

evtx file has ElFile sig in first 7 bytes and was generated from Microsoft DNS Server.

```
$ python ./evtx_dump.py ../data/ITBDNS04-AnalyticalLog-9Nov2016-1.evtx 
Traceback (most recent call last):
  File "./evtx_dump.py", line 42, in <module>
    main()
  File "./evtx_dump.py", line 34, in main
    print(e_views.XML_HEADER)
AttributeError: 'module' object has no attribute 'XML_HEADER'
```

**Comment by williballenthin** [comment]
hey @stephensheridan 

i suspect that perhaps you have an older version of the library also installed, which doesn't have this updated header field. if you've recently downloaded the latest source directory, then you'll need to ensure you've also installed the library, or Python may pick the older library (even though its running the new script).

easiest way is probably:

    pip install --upgrade python-evtx

if that doesn't work, let me know, and i can walk you through some troubleshooting.

**Comment by stephensheridan** [comment]
Yip, installed new libraries with pip update and solved issue. 

Thank you.
