### ISSUE TITLE
TypeError when running evtx_eid_record_numbers.py script

### ISSUE THREAD

**Issue by plapornik** [williballenthin/python-evtx#50]
Hi Willi,

I'm getting the following error when running the **evtx_eid_record_numbers.py** script:
TypeError: 'method' object is not iterable

I've debugged the script and worked out that line 23 should be:
`for record in log.records():`
instead of:
`for record in log.records:`

Regards,
Peter

**Comment by williballenthin** [comment]
great catch, thanks!

**Comment by williballenthin** [comment]
addressed in 946dee52e861a517a3ae33290f7e5e1d3d99f090
