### ISSUE TITLE
Evtx.py - Python 3: sys.maxint constant was removed, use sys.maxsize instead

### ISSUE THREAD

**Issue by goorgoorlou** [williballenthin/python-evtx#52]
https://github.com/williballenthin/python-evtx/blob/master/Evtx/Evtx.py#L232

https://docs.python.org/3.1/whatsnew/3.0.html#integers

The sys.maxint constant was removed, since there is no longer a limit to the value of integers. However, sys.maxsize can be used as an integer larger than any practical list or string index. It conforms to the implementation’s “natural” integer size and is typically the same as sys.maxint in previous releases on the same platform (assuming the same build options).

Thank you! Best regards!

**Comment by williballenthin** [comment]
great catch, thanks!
