### ISSUE TITLE
setup.py issues on Ubuntu 18.04.3, pip pinning needed

### ISSUE THREAD

**Issue by atcuno** [williballenthin/python-evtx#67]
A number of dependencies are broken on latest 18.04 LTS. Most of them seem to be the packages moving onto Python 3. To get it working, I had to pin the following with pip:

pip install more_itertools==5.0.0
pip install zipp==1.0.0
pip install configparser==4.0.2
pip install pyparsing==2.4.7

Pretty sure you could add these specifically in setup.py to get a clean install.

**Comment by williballenthin** [comment]
added in 1ea9d044f43e3c83ea887fb6901ddbcce199f824
