### ISSUE TITLE
AttributeError: module 'evtx' has no attribute 'Evtx'

### ISSUE THREAD

**Issue by Squiblydoo** [williballenthin/python-evtx#73]
I feel like I must be making some stupid mistake, but I haven't been able to find the solution after a few hours of poking around.

![image](https://user-images.githubusercontent.com/77356206/129447207-a4bce02a-6b37-41f2-a2f8-49b5c21dd96e.png)
Using Windows 10 and using Python 3.9.1, if I install python-evtx using "python -m pip install python-evtx"; then import the module and try to use it, I consistently get an error which states the attributes do not exist. 

On the other hand, IDLE appears to see the modules and auto suggests them. 
![image](https://user-images.githubusercontent.com/77356206/129447305-324dcea0-d5e9-43f9-b81e-432f602ac84d.png)

Is there something I am missing to get this to work correctly? 
I appear to be having the same issue on Linux. 
I don't believe the issue is in regards to how I am importing python-evtx as I have been unable to use a number of projects that use Python-Evtx; they all seem to break at calling Evtx or View.

Thank you for any help that you can provide.

**Comment by williballenthin** [comment]
In short:
![image](https://user-images.githubusercontent.com/156560/129499245-f483a5f1-597c-4775-ae63-c107005e076f.png)

More detail:
When I first started to develop this library (back in 2013 :-O) I didn't think enough about the module layout and so we end up with slightly confusing fully-qualified module/class names.

The project is `Evtx` and so there's a top level namespace `Evtx`.
There's a primary file that contains top level structures and so there's a mid level namespace `Evtx.Evtx`.
And within this file is a class named.... you guess it, `Evtx`, so the class you're trying to reference is `Evtx.Evtx.Evtx`. I'm sorry 🤦🏼 

To debug this yourself, you can use `dir(any instance, including modules)` to see all the names available under that instance, e.g.
![image](https://user-images.githubusercontent.com/156560/129499472-9ed1de39-e18c-4821-8b97-ae04c1aa4bc1.png)

Final note, using the name `evtx` might kinda sorta work on Windows, which by default uses NTFS that is *not* case sensitive, but this is not portable and might break in weird places.

**Comment by williballenthin** [comment]
Feel free to re-open this issue with any further questions or problems - happy to help!

**Comment by williballenthin** [comment]
you could also take a look at how the example scripts do their imports:
https://github.com/williballenthin/python-evtx/blob/master/scripts/evtx_dump.py#L20-L21

![image](https://user-images.githubusercontent.com/156560/129499626-20469ce9-41e2-4dba-95a0-2ea5ecd8bbbc.png)
