### ISSUE TITLE
Update project url?

### ISSUE THREAD

**Issue by sodface** [williballenthin/python-evtx#78]
Hello, what is the preferred url to use for this project? The url listed on the main repo page is dead:
http://www.williballenthin.com/evtx/index.html

**Comment by williballenthin** [comment]
the url should point to this repo: https://github.com/williballenthin/python-evtx

however, I don't see the link you're referring to?

![image](https://user-images.githubusercontent.com/156560/151197833-ff778fc8-4013-4e2e-b0f3-ee5473a9506b.png)

**Comment by sodface** [comment]
Thanks for the clarification. The URL I was asking about is on the main repo page near the license. This screenshot is from my mobile phone, in a non mobile layout it's on the right side but still near the license. 

![Screenshot_20220126-132259](https://user-images.githubusercontent.com/46695384/151224682-f91907ac-bbbe-4bb3-a65a-ee5060b668fb.png)

**Comment by williballenthin** [comment]
ahh, thank you!

**Comment by williballenthin** [comment]
fixed (by removing the link)
