### ISSUE TITLE
Dump in JSON format

### ISSUE THREAD

**Issue by ajread4** [williballenthin/python-evtx#81]
I forked your work and modified evtx_dump.py (named to evtx_dump_json.py) to write output to a JSON file or to standard out. My use case is for graph learning research and I like to use JSON files (converted into Pandas Dataframes) as input. 

Is there any interest in adding that functionality? I was thinking about doing a PR but I figured I should ask before doing so.

**Comment by williballenthin** [comment]
neat!

sure, happy to merge a new script, though I likely won't be able to offer support for it. i'll tag you on any future issues opened on Github and/or it can serve as an example to others.

thank you!

**Comment by ajread4** [comment]
great! I will clean up some of the code and put in a PR. Feel free to tag me for future issues, I am more than happy to help out!
