### ISSUE TITLE
Loop through the records in reversed order

### ISSUE THREAD

**Issue by CaledoniaProject** [williballenthin/python-evtx#86]
How can I loop through the records from bottom up?

**Comment by williballenthin** [comment]
the easiest way will be to parse all the events and then reverse the list. 

it's probably possible to enumerate the chunks in reverse order, and from there get the events from each chunk and reverse them. this will require you to take a look into this library's code and understand it a bit. there is not a built in routine for this use case and the file format also isn't designed for it.
